language: java
jdk:
  - oraclejdk11
before_install:
  - sudo apt-get update
  - cd app/
  - echo "Let's start Maven Package!!!"
  - mvn clean package
  - cd ..
  - echo "We are in root dir"
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker push leandrocgsi/docker-from-zero-to-mastery-java;
  on:
    brach: master
notifications:
  email: false